services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures services
  WechatOfficialAccountStatsBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']